// Prop firm data. Fintokei values are sourced from fintokei-raw.json (Tým 1, 05/2026).
// Other firms remain mock placeholders.

// Account sizes (USD) available across all firms
window.ACCOUNT_SIZES = [10000, 25000, 50000, 100000, 200000];

// Helper: price for a given firm + selected account size (USD). Falls back to 25k.
window.priceFor = function (firm, size) {
  if (firm.prices && firm.prices[size] != null) return firm.prices[size];
  return firm.challengePrice;
};

window.PROP_FIRMS = [
  {
    // ── FINTOKEI — data ze zdroje fintokei-raw.json (Tým 1, 05/2026) ──────────
    // Reprezentativní challenge: ProTrader (2-fázová). Ceny dle dostupných velikostí;
    // $25k mapováno na nejbližší ProTrader 20k ($159).
    id: 'fintokei',
    name: 'Fintokei',
    initials: 'FK',
    tagline: 'Purple Group · Brno + Tokyo',
    brand: { from: '#6B03E5', to: '#F815B3' },
    // ── Hlavní řádek ───────────────────────────────────────
    prices:           { 10000: 99, 25000: 159, 50000: 319, 100000: 529, 200000: 1149 },
    challengePrice:   159,       // ProTrader 20k (nejbližší k $25k)
    profitTargetP1:   8,         // ProTrader phase 1
    steps:            2,         // ProTrader = 2-fázová
    maxDailyDD:       5,
    maxOverallDD:     10,
    payoutSplit:      80,        // ProTrader fixed split
    payoutFreq:       'Bi-weekly',
    firstPayoutDays:  7,         // bi-weekly, approval ~2.8 sec
    popularity:       82,        // overallPopularityScore 81.9 (Trustpilot 4.5 · 1137 reviews)
    supportRating:    4.5,       // Trustpilot score
    supportNote:      '24/7 chat · CZ/EN/JA/IT',
    activeCampaign:   '−20 % na vše (kód NEW20)',
    // ── Rozbalovací detail ─────────────────────────────────
    timeMin:          3,         // minTradingDaysPerPhase
    timeMax:          null,      // noTimeLimitOnFundedAccount
    newsTrading:      true,
    maxLeverage:      '1:100',   // ProTrader forex/gold
    avgPayout:        3881,      // avgPayoutUSD (payoutStats)
    robotsAllowed:    true,      // vlastní/upravené EA; komerční a copy trading zakázány
    mobileApp:        true,
    platforms:        ['TradingView', 'MT5', 'cTrader'],
    loyaltyProgram:   true,      // XP-based: +25% kapitál, free challange účty až $100K
    foundedYear:      2023,      // yearsInOperation: 3
    paymentMethods:   ['Visa/JCB', 'Apple Pay', 'Google Pay', 'Krypto', 'SEPA', 'JPY transfer', 'Walletory'],
    restrictedCountries: ['US', 'IN', 'RU', 'BY', 'KP', 'IR', 'MM', 'SY', 'YE', 'CU', 'VE', 'SD', 'SS', 'AF', 'SO', 'IQ'],
    // ── Pro section-attributes & section-news ──────────────
    phases:           2,
    phasesLabel:      '2-fázová',
    refundable:       false,
    weekendHolding:   true,
    regions:          'Globální (mimo US/IN/RU)',
    supportLangs:     4,         // cs, en, ja, it
    sentiment:        'positive',
    sentimentScore:   82,
    sentimentSummary: 'Traders chválí sub-sekundové výplaty (€29M+/rok) a XP loyalty program. Výhrady k Consistency Rules a permanentním banům bez odvolání.',
    news: { headline: 'Spuštěn ProTrader Swing 50k — DD počítán z balance, ne equity', date: '15. 5. 2026', tag: 'Produkt' }
  },
  {
    id: 'ftmo',
    name: 'FTMO',
    initials: 'FT',
    tagline: 'Prague, est. 2014',
    brand: { from: '#0F172A', to: '#1E40AF' },
    prices:           { 10000: 89,  25000: 155, 50000: 270, 100000: 540, 200000: 1080 },
    challengePrice:   155,
    profitTargetP1:   10,
    steps:            2,
    maxDailyDD:       5,
    maxOverallDD:     10,
    payoutSplit:      80,
    payoutFreq:       'Měsíčně',
    firstPayoutDays:  30,
    popularity:       95,
    supportRating:    4.6,
    supportNote:      '24/7 chat + email',
    activeCampaign:   null,
    timeMin:          4,
    timeMax:          null,
    newsTrading:      false,
    maxLeverage:      '1:100',
    avgPayout:        3200,
    robotsAllowed:    true,
    mobileApp:        true,
    platforms:        ['MT4', 'MT5', 'cTrader', 'DXtrade'],
    loyaltyProgram:   true,
    foundedYear:      2014,
    paymentMethods:   ['Karta', 'Krypto', 'Wire', 'PayPal'],
    restrictedCountries: ['USA', 'Severní Korea', 'Írán', 'Sýrie'],
    phases:           2,
    phasesLabel:      '2-fázová',
    refundable:       true,
    weekendHolding:   false,
    regions:          'Globální (180+)',
    supportLangs:     17,
    sentiment:        'positive',
    sentimentScore:   71,
    sentimentSummary: 'Standard branže, ale komunita kritizuje přísná pravidla a 2-fázovou strukturu.',
    news: { headline: 'FTMO mění strop na maximální velikost účtu z $400k na $200k', date: '11. 5. 2026', tag: 'Pravidla' }
  },
  {
    id: 'fundednext',
    name: 'FundedNext',
    initials: 'FN',
    tagline: 'UAE, est. 2022',
    brand: { from: '#22C55E', to: '#0EA5E9' },
    prices:           { 10000: 59,  25000: 89,  50000: 179, 100000: 329, 200000: 549 },
    challengePrice:   89,
    profitTargetP1:   8,
    steps:            2,
    maxDailyDD:       5,
    maxOverallDD:     10,
    payoutSplit:      85,
    payoutFreq:       'Měsíčně',
    firstPayoutDays:  14,
    popularity:       82,
    supportRating:    4.4,
    supportNote:      '24/7 chat',
    activeCampaign:   '−50 % Stellar Lite',
    timeMin:          5,
    timeMax:          null,
    newsTrading:      true,
    maxLeverage:      '1:100',
    avgPayout:        1800,
    robotsAllowed:    true,
    mobileApp:        true,
    platforms:        ['MT4', 'MT5', 'cTrader'],
    loyaltyProgram:   false,
    foundedYear:      2022,
    paymentMethods:   ['Karta', 'Krypto', 'Wire'],
    restrictedCountries: ['USA', 'Severní Korea'],
    phases:           2,
    phasesLabel:      '2-fázová',
    refundable:       true,
    weekendHolding:   true,
    regions:          'Globální mimo USA',
    supportLangs:     6,
    sentiment:        'mixed',
    sentimentScore:   58,
    sentimentSummary: 'Pozitivní zpětná vazba k cenám, smíšené k vyplácení větších částek.',
    news: { headline: 'FundedNext spouští "Stellar Lite" — instantní funded účet za $49', date: '14. 5. 2026', tag: 'Akce' }
  },
  {
    id: 'e8',
    name: 'E8 Markets',
    initials: 'E8',
    tagline: 'Texas, est. 2021',
    brand: { from: '#F97316', to: '#EA580C' },
    prices:           { 10000: 139, 25000: 198, 50000: 388, 100000: 688, 200000: 1100 },
    challengePrice:   198,
    profitTargetP1:   8,
    steps:            2,
    maxDailyDD:       5,
    maxOverallDD:     8,
    payoutSplit:      80,
    payoutFreq:       'Týdně',
    firstPayoutDays:  21,
    popularity:       65,
    supportRating:    4.2,
    supportNote:      'Po–Pá chat',
    activeCampaign:   null,
    timeMin:          0,
    timeMax:          null,
    newsTrading:      true,
    maxLeverage:      '1:100',
    avgPayout:        1500,
    robotsAllowed:    true,
    mobileApp:        false,
    platforms:        ['MT4', 'MT5'],
    loyaltyProgram:   false,
    foundedYear:      2021,
    paymentMethods:   ['Karta', 'Krypto'],
    restrictedCountries: ['Severní Korea', 'Írán', 'Sýrie'],
    phases:           2,
    phasesLabel:      '2-fázová',
    refundable:       false,
    weekendHolding:   false,
    regions:          'Globální',
    supportLangs:     4,
    sentiment:        'mixed',
    sentimentScore:   55,
    sentimentSummary: 'Diskuse kolem nové cenové struktury — někteří vidí zdražení.',
    news: { headline: 'E8 Markets navyšuje payout split u "Elite" účtu na 95 %', date: '8. 5. 2026', tag: 'Produkt' }
  },
  {
    id: 'the5ers',
    name: 'The 5%ers',
    initials: '5%',
    tagline: 'Israel, est. 2016',
    brand: { from: '#0EA5E9', to: '#6366F1' },
    prices:           { 10000: 145, 25000: 235, 50000: 425, 100000: 775, 200000: 1295 },
    challengePrice:   235,
    profitTargetP1:   6,
    steps:            1,
    maxDailyDD:       0,
    maxOverallDD:     4,
    payoutSplit:      75,
    payoutFreq:       'Měsíčně',
    firstPayoutDays:  14,
    popularity:       72,
    supportRating:    4.3,
    supportNote:      '24/7 chat',
    activeCampaign:   'Free reset (do vyprodání)',
    timeMin:          6,
    timeMax:          null,
    newsTrading:      true,
    maxLeverage:      '1:30',
    avgPayout:        1100,
    robotsAllowed:    false,
    mobileApp:        false,
    platforms:        ['MT5', 'TradingView'],
    loyaltyProgram:   true,
    foundedYear:      2016,
    paymentMethods:   ['Karta', 'Wire', 'PayPal'],
    restrictedCountries: ['Severní Korea', 'Írán'],
    phases:           1,
    phasesLabel:      '1-fázová',
    refundable:       false,
    weekendHolding:   true,
    regions:          'Globální',
    supportLangs:     5,
    sentiment:        'positive',
    sentimentScore:   69,
    sentimentSummary: 'Známí jako "low-risk" prop — méně agresivní DD, ale dražší vstup.',
    news: { headline: 'The 5%ers zavádí scaling plan — automatické navýšení po 3 výplatách', date: '6. 5. 2026', tag: 'Produkt' }
  },
  {
    id: 'fundingpips',
    name: 'FundingPips',
    initials: 'FP',
    tagline: 'UAE, est. 2022',
    brand: { from: '#10B981', to: '#06B6D4' },
    prices:           { 10000: 49,  25000: 79,  50000: 149, 100000: 299, 200000: 599 },
    challengePrice:   79,
    profitTargetP1:   8,
    steps:            2,
    maxDailyDD:       5,
    maxOverallDD:     10,
    payoutSplit:      80,
    payoutFreq:       'Bi-weekly',
    firstPayoutDays:  14,
    popularity:       79,
    supportRating:    4.5,
    supportNote:      '24/7 chat',
    activeCampaign:   '−15 % na vše',
    timeMin:          3,
    timeMax:          null,
    newsTrading:      true,
    maxLeverage:      '1:100',
    avgPayout:        1900,
    robotsAllowed:    true,
    mobileApp:        false,
    platforms:        ['MT4', 'MT5', 'cTrader'],
    loyaltyProgram:   false,
    foundedYear:      2022,
    paymentMethods:   ['Karta', 'Krypto'],
    restrictedCountries: ['USA', 'Severní Korea'],
    phases:           2,
    phasesLabel:      '2-fázová',
    refundable:       true,
    weekendHolding:   true,
    regions:          'Globální',
    supportLangs:     3,
    sentiment:        'positive',
    sentimentScore:   67,
    sentimentSummary: 'Levný vstup, dobrá reputace na Reddit /r/Forex.',
    news: { headline: 'FundingPips otevírá office v Dubaji a najímá 30 lidí', date: '12. 5. 2026', tag: 'Firma' }
  },
  {
    id: 'topstep',
    name: 'Topstep',
    initials: 'TS',
    tagline: 'Chicago, est. 2012',
    brand: { from: '#DC2626', to: '#991B1B' },
    prices:           { 10000: 99,  25000: 165, 50000: 325, 100000: 550, 200000: 950 },
    challengePrice:   165,
    profitTargetP1:   6,
    steps:            1,
    maxDailyDD:       3,
    maxOverallDD:     6,
    payoutSplit:      90,
    payoutFreq:       '2× měsíčně',
    firstPayoutDays:  8,
    popularity:       70,
    supportRating:    4.5,
    supportNote:      'Po–Pá tel. + chat',
    activeCampaign:   '$50K Combine za $99 (do 31. 5.)',
    timeMin:          2,
    timeMax:          null,
    newsTrading:      true,
    maxLeverage:      '1:50',
    avgPayout:        1700,
    robotsAllowed:    false,
    mobileApp:        true,
    platforms:        ['NinjaTrader', 'TradingView', 'Tradovate'],
    loyaltyProgram:   true,
    foundedYear:      2012,
    paymentMethods:   ['Karta', 'Wire', 'ACH'],
    restrictedCountries: ['Severní Korea', 'Írán', 'Kuba'],
    phases:           1,
    phasesLabel:      '1-fázová',
    refundable:       false,
    weekendHolding:   false,
    regions:          'USA + EU',
    supportLangs:     2,
    sentiment:        'positive',
    sentimentScore:   73,
    sentimentSummary: 'Futures-only veterán. Stabilní výplaty, ale úzké DD.',
    news: { headline: 'Topstep snižuje cenu $50K Combine na $99 do konce května', date: '18. 5. 2026', tag: 'Akce' }
  },
  {
    id: 'fxcomet',
    name: 'FX Comet',
    initials: 'FX',
    tagline: 'Belize, est. 2024',
    brand: { from: '#A78BFA', to: '#EC4899' },
    prices:           { 10000: 69,  25000: 119, 50000: 229, 100000: 399, 200000: 679 },
    challengePrice:   119,
    profitTargetP1:   10,
    steps:            1,
    maxDailyDD:       5,
    maxOverallDD:     12,
    payoutSplit:      90,
    payoutFreq:       'Týdně',
    firstPayoutDays:  5,
    popularity:       38,
    supportRating:    3.6,
    supportNote:      'Email only',
    activeCampaign:   '−40 % launch sale',
    timeMin:          5,
    timeMax:          30,
    newsTrading:      true,
    maxLeverage:      '1:200',
    avgPayout:        900,
    robotsAllowed:    true,
    mobileApp:        false,
    platforms:        ['MT5', 'cTrader'],
    loyaltyProgram:   false,
    foundedYear:      2024,
    paymentMethods:   ['Karta', 'Krypto'],
    restrictedCountries: ['USA', 'Severní Korea', 'Írán'],
    phases:           1,
    phasesLabel:      '1-fázová',
    refundable:       true,
    weekendHolding:   true,
    regions:          'Globální',
    supportLangs:     4,
    sentiment:        'mixed',
    sentimentScore:   52,
    sentimentSummary: 'Nový hráč. Lákavý 90% split, ale málo data o výplatách.',
    news: { headline: 'FX Comet ohlašuje partnership s cTrader pro futures', date: '10. 5. 2026', tag: 'Partnerství' }
  }
];

// Attributes the user can weight in section 3
// direction: 'higher' = bigger value is better; 'lower' = smaller is better; 'bool' = true is better
window.ATTRIBUTES = [
  { key: 'challengePrice',  label: 'Nízká cena výzvy',       hint: 'USD za výzvu (dle account size)', direction: 'lower',  unit: '$', format: (v)=>`$${v}` },
  { key: 'payoutSplit',     label: 'Vysoký payout split',    hint: '% co si trader nechá',           direction: 'higher', unit: '%', format: (v)=>`${v}%` },
  { key: 'maxOverallDD',    label: 'Velkorysý max drawdown', hint: 'celkový strop ztrát',            direction: 'higher', unit: '%', format: (v)=>`${v}%` },
  { key: 'profitTargetP1',  label: 'Nízký profit target',    hint: 'kolik musíš vydělat ve fázi 1',   direction: 'lower',  unit: '%', format: (v)=>`${v}%` },
  { key: 'firstPayoutDays', label: 'Rychlá první výplata',   hint: 'dní od pasování',                direction: 'lower',  unit: 'd', format: (v)=>`${v} d` },
  { key: 'steps',           label: 'Méně fází výzvy',        hint: '1-fázová vs 2-fázová',           direction: 'lower',  unit: '',  format: (v)=>`${v} fáze` },
  { key: 'popularity',      label: 'Populární firma',        hint: 'agregovaný score',               direction: 'higher', unit: '',  format: (v)=>`${v}/100` },
  { key: 'supportRating',   label: 'Špičkový support',       hint: 'hodnocení uživatelů',            direction: 'higher', unit: '/5', format: (v)=>`${v}/5` },
  { key: 'refundable',      label: 'Vrátitelný poplatek',    hint: 'získáš zpět po pasování',        direction: 'bool',   unit: '',  format: (v)=>v?'Ano':'Ne' },
  { key: 'weekendHolding',  label: 'Držení přes víkend',     hint: 'možnost swing-trade',            direction: 'bool',   unit: '',  format: (v)=>v?'Ano':'Ne' },
  { key: 'mobileApp',       label: 'Mobilní aplikace',       hint: 'iOS + Android',                  direction: 'bool',   unit: '',  format: (v)=>v?'Ano':'Ne' },
  { key: 'loyaltyProgram',  label: 'Loyalty program',        hint: 'odměny za věrnost',              direction: 'bool',   unit: '',  format: (v)=>v?'Ano':'Ne' }
];
